# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [2]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2] # corpus

In [3]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [4]:
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [5]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil "
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [7]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [8]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

                   Data is the oil   Data is a new oil
Data is the oil            1.000000           0.602975
Data is a new oil          0.602975           1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [9]:
pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gensim in c:\users\n\appdata\roaming\python\python313\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\programdata\anaconda3\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in c:\programdata\anaconda3\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\n\appdata\roaming\python\python313\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in c:\programdata\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [11]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")

print("Path to dataset files:", path)
#fake-and-real-news-dataset-true.csv

Path to dataset files: C:\Users\N\.cache\kagglehub\datasets\clmentbisaillon\fake-and-real-news-dataset\versions\1

In [12]:
import pandas as pd
import numpy as np
import os

print(os.listdir(path))

['Fake.csv', 'True.csv']

In [13]:
df=pd.read_csv(path+"/True.csv")
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [14]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)
# tokenization of the text column

In [15]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)# here convert tokens to vector
# window=5, if word appeared 5 times find its vector, othwerwise skip
# vector of size 100, its better to has big vector size

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

In [16]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))
# similarity between two words

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.4174624

In [17]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))
# outputs words similiar to the word program

words that similar to 'program' - Skip Gram :  [('programme', 0.815785825252533), ('programs', 0.8042788505554199), ('EB-5', 0.6946887969970703), ('arsenal', 0.6945032477378845), ('modernization', 0.6852651238441467), ('guest-worker', 0.6705517768859863), ('bond-buying', 0.6685560345649719), ('nuclear', 0.6681990623474121), ('abolishing', 0.6661299467086792), ('programmes', 0.6632733941078186)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [18]:
# 1) data
doc1 = "This is the first document."
doc2 = "This document is the second document."
doc3 = "And this is the third one."
doc4 = "Is this the first document?"

data = [doc1, doc2, doc3, doc4]

In [19]:
# 2) convert data to vectors
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [20]:
# 3) apply cosine to vector metrix

cosine_similarity_matrix = cosine_similarity(vector_matrix)
df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)
df_cosine

,This is the first document.,This document is the second document.,And this is the third one.,Is this the first document?
This is the first document.,1.000000,0.646926,0.307772,1.000000
This document is the second document.,0.646926,1.000000,0.225240,0.646926
And this is the third one.,0.307772,0.225240,1.000000,0.307772
Is this the first document?,1.000000,0.646926,0.307772,1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [24]:
# 1) data
dc1 = "data science is one of the most important fields of science"
dc2 = "this is one of the best data science courses"
dc3 = "data scientists analyze data"
data = [dc1, dc2, dc3]

In [25]:
# 2) use TF-IDF 
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data)

In [26]:
# 3) display result, frequent words get lower score
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
0,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
1,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
2,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [33]:
df=pd.read_csv('lab5/simpsons_script_lines.csv')
df.head()

        raw_character_text                                       spoken_words
0              Miss Hoover  No, actually, it was a little of both. Sometim...
1             Lisa Simpson                             Where's Mr. Bergstrom?
2              Miss Hoover  I don't know. Although I'd sure like to talk t...
3             Lisa Simpson                         That life is worth living.
4  Edna Krabappel-Flanders  The polls will be open from now until the end ...

In [41]:
import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

In [60]:
df['spoken_words'] = df['spoken_words'].fillna('').apply(clean_text) # fillna used here to avoid the tokenization error
df['spoken_words'].head()

0    no actually it was a little of both sometimes ...
1                                where's mr bergstrom?
2    i don't know although i'd sure like to talk to...
3                            that life is worth living
4    the polls will be open from now until the end ...
Name: spoken_words, dtype: object

In [46]:
tokens = []

for i in df['spoken_words']:
    token = word_tokenize(i)
    tokens.append(token)
# tokenization

In [47]:
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'
Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [50]:
print("words that similar to 'homer' - Skip Gram : ",Skip_gram_model.wv.most_similar('homer'))

words that similar to 'homer' - Skip Gram :  [('abe', 0.888937771320343), ('marge', 0.8566890954971313), ('bart', 0.8273546695709229), ('bartholomew', 0.8225709795951843), ('grampa', 0.8212049603462219), ('ned', 0.8123763203620911), ('eliza', 0.8074812293052673), ('mindy', 0.8074466586112976), ('apu', 0.8050538897514343), ('allison', 0.8019753694534302)]

In [51]:
print("words that similar to 'marge' - Skip Gram : ",Skip_gram_model.wv.most_similar('marge'))

words that similar to 'marge' - Skip Gram :  [('abe', 0.860596776008606), ('homer', 0.8566890954971313), ('sweetie', 0.8266910910606384), ('honey', 0.8219273686408997), ('lisa', 0.8204267621040344), ('allison', 0.8186200261116028), ('becky', 0.8178800344467163), ('apu', 0.8148435354232788), ('sweetheart', 0.8135912418365479), ('aww', 0.8102978467941284)]

In [52]:
print("words that similar to 'bart' - : ",Skip_gram_model.wv.most_similar('bart'))

words that similar to 'bart' - :  [('lisa', 0.8954393863677979), ('milhouse', 0.8802508115768433), ('grampa', 0.8584704399108887), ('abe', 0.8581019043922424), ('sweetie', 0.8478620648384094), ('kirk', 0.8389559388160706), ('allison', 0.8363167643547058), ('janey', 0.8354699015617371), ('jessica', 0.8344079256057739), ('homer', 0.8273547291755676)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [56]:
list1=['jimbo', 'milhouse', 'kearney']
print("Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list: ",Skip_gram_model.wv.doesnt_match(list1) )

Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list:  milhouse

In [58]:
list2=["nelson", "bart", "milhouse"]
print(' odd one among "nelson", "bart", and "milhouse": ', Skip_gram_model.wv.doesnt_match(list2) )

 odd one among "nelson", "bart", and "milhouse":  nelson

In [59]:
list3=["homer", "patty", "selma"]
print(" odd one among ‘homer', 'patty', and ‘selma' : " , Skip_gram_model.wv.doesnt_match(list3) )

 odd one among ‘homer', 'patty', and ‘selma' :  homer